apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: stedi
  template:
    metadata:
      labels:
        app: stedi
    spec:
      containers:
      - name: stedi-container
        image: placeholder-registry/placeholder-stedi-image:latest  # Replace with your actual image details
        ports:
        - containerPort: 80  # Adjust the port if needed
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-service
spec:
  selector:
    app: stedi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Specify the desired node port
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-ingress
spec:
  rules:
  - host: placeholder-stedi-domain.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-service
            port:
              number: 80
  tls:
  - hosts:
    - placeholder-stedi-domain.com  # Replace with your actual domain
    secretName: stedi-tls-secret
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-tls-certificate
spec:
  domains:
  - placeholder-stedi-domain.com  # Replace with your actual domain
---
